book_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import index, filter_view
from book_tracker import urls

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path(route='filter_view/', view=filter_view, name="filter_view"),
    path('books/', include(('books.urls', 'books'), namespace='books')), #to do books: need to add this namespace
]

books/urls.py
from django.urls import path
from .import views

from django.conf.urls.static import static
from django.conf import settings

app_name = 'books'

urlpatterns = [
    path(route='', view=views.index),
    # path(route='logout', view=views.logout_request, name='logout'),
    path(route='user_login/', view=views.login_request, name='login'),
    path(route='suggested_books/', view=views.get_suggested_books, name='suggested_books'),
    path(route='user_logout/', view=views.logout_request, name='logout'),
    path(route='whyNot/', view=views.whyNot, name='whyNot'),
    path(route='add_throne/', view=views.add_throne, name='add_throne'),
    path(route='add_book/', view=views.add_book, name='add_book'),
    path(route='create_account/', view=views.create_account, name='create_account')
]

templates/add_book_popup.html
{% extends "index.html" %}

{% block content %}

{% load static %}
<div id="popup1" class="overlay">
    <div class="popup">
        <h2>Here i am</h2>
        <a class="close" href="#">&times;</a>

        <div class="content container" >

            <div class="left-menu" style="min-height: 60vh;">
                <img src="https://cdn.vectorstock.com/i/1000v/52/86/red-cartoon-question-mark-vector-51155286.jpg"
                 style="width: 100%; border-radius: 10px;" id="current_book_cover">
            </div>

            <div class="right-menu" style="min-height: 60vh;">
                <form action="{% url 'books:add_book' %}" method="post" id="add_book">
                    {% csrf_token %}

                    {% comment %} book title input field {% endcomment %}
                    <div style="display: flex; justify-content: center">
                        <p>Book Title:        </p>
                        <ul class="book-list">
                            <input type="text" placeholder="Enter Book Title: " name="book_title" id="book_title" style="width: 100%; height: 40px" required>
                            <input type="text" name="book_cover" id="book_cover" style="width: 100%; height: 20px; display: none" required>
                            <div id="suggestions">
                            </div>

                        </ul>
                    </div>
                    
                    {% comment %} book title submission button {% endcomment %}
                    <button type="button" id="generate_suggestions" 
                        hx-post="/books/suggested_books/" hx-target="#suggestions" hx-swap="innerHTML">
                        Search For Book!
                    </button>
                    
                    {% comment %} author input field (auto fills) {% endcomment %}
                    <div style="display: flex; justify-content: center">
                        <p>Author:        </p>
                        <input type="text" placeholder="Enter Book Author: " name="book_author" id="book_author"  required>
                        <p id="randooo">yello</p>
                    </div>

                    {% comment %} Display the different genre options {% endcomment %}
                    <div style="display: flex; justify-content: center; flex-wrap: wrap">
                        {% for eachGenre in all_unique_genres%}

                        <button class="genre-container genre-select" type="button" style="background-color: {{ eachGenre.color }};" onclick="select_genre(this)">
                            {{ eachGenre.title }}
                        </button>

                        {% endfor %}
                        <input type="text" name="genres_selected" id="genres_selected" style="display:none">
                    </div>

                    <br>

                    {% comment %} Display the stars {% endcomment %}
                    <div style="display: flex; justify-content: center">
                        <div style="display: flex; justify-content: space-between; width: 50%" id="all_stars">
                            <button class="star" id="one_star" onclick="click_star(this)" type="button">
                                <img src="{% static 'images/star-outline.png' %}" style="width: 100%">
                            </button>

                            <button class="star" id="two_star" onclick="click_star(this)" type="button">
                                <img src="{% static 'images/star-outline.png' %}" style="width: 100%">
                            </button>

                            <button class="star" id="three_star" onclick="click_star(this)" type="button">
                                <img src="{% static 'images/star-outline.png' %}" style="width: 100%">
                            </button>

                            <button class="star" id="four_star" onclick="click_star(this)" type="button">
                                <img src="{% static 'images/star-outline.png' %}" style="width: 100%">
                            </button>

                            <button class="star" id="five_star" onclick="click_star(this)" type="button">
                                <img src="{% static 'images/star-outline.png' %}" style="width: 100%">
                            </button>
                        </div>

                        <input id="star_rating" name="star_rating">1</input>
                    </div>
                    <p id="yello">bhello</p>

                    <button type="submit">Add Log!</button>
                    <br>
                </form>
            </div>
        </div>
    </div>

    </div>

    <script>
        const all_stars = document.getElementById("all_stars").children;
        const nums = ["one", "two", "three", "four", "five"]

        let hover_of = true;

        for (const star of all_stars) {
            document.getElementById("randooo").innerText = "whhwhwhwh";
            star.addEventListener('mouseover', function() {
                //document.getElementById("randooo").innerText = hover_of;
                let filledNum = star.id.substring(0, star.id.indexOf("_"));
                let filledIndex = nums.indexOf(filledNum);
                //document.getElementById("randooo").innerText = filledIndex;

                for (let i = 0; i <= filledIndex; i++) {
                    document.getElementById(nums[i] + "_star").children[0].src = "{% static 'images/star-filled.png' %}";
                }
                for (let i = filledIndex+1; i < all_stars.length; i++) {
                    document.getElementById(nums[i] + "_star").children[0].src = "{% static 'images/star-outline.png' %}";
                }

                hover_of = true;
            });
            star.addEventListener('mouseout', function() {
                //document.getElementById("randooo").innerText = hover_of;
                if (hover_of) {
                    for (let i = 0; i < all_stars.length; i++) {
                        document.getElementById(nums[i] + "_star").children[0].src = "{% static 'images/star-outline.png' %}";
                    }
                }
            });
        }
        
        function click_star(star) {
            hover_of = false;

            let filledNum = star.id.substring(0, star.id.indexOf("_"));

            document.getElementById("randooo").innerText = star.id.indexOf("_");
            
            let filledIndex = nums.indexOf(filledNum);

            for (let i = 0; i <= filledIndex; i++) {
                document.getElementById(nums[i] + "_star").children[0].src = "{% static 'images/star-filled.png' %}";
            }
            for (let i = filledIndex+1; i < all_stars.length; i++) {
                document.getElementById(nums[i] + "_star").children[0].src = "{% static 'images/star-outline.png' %}";
            }
            document.getElementById("star_rating").value = filledIndex + 1;
        }

        var buttonsSelected = []
        function select_genre(element) {
            var buttons = element.parentElement.getElementsByClassName("genre-select");
            
            if (element.classList.contains("active")) {
                element.classList.remove("active");
                if (buttonsSelected.includes(element.innerText)) {
                    buttonsSelected = buttonsSelected.filter(item => item !== element.innerText);
                }
            } else {
                element.classList.add("active");
                buttonsSelected.push(element.innerText);
            }

            document.getElementById("genres_selected").value = buttonsSelected;
        }
    </script>
{%endblock%}

templates/all_books_view.html
{% load static %}

{% for each_row in books_and_genres%}
    <div class="book-container">
    {% for each_book_and_genres in each_row %}
        {% if each_book_and_genres != -1%}

        <div class="book" style="display:flex;">

            <div style="width: 43%; background-color: pink; border-radius: 15px; align-content: center">
                <img src="{{each_book_and_genres.book.cover}}" 
                alt="Italian Trulli" style="height: 95%; border-radius: 10px;">
            </div>

            <div style="width: 57%; border-radius: 15px; padding-left: 15px; padding-right: 15px;">
                <h2 style="text-align: left">{{each_book_and_genres.book.title}}</h2>
                <p style="text-align: left">{{each_book_and_genres.book.author}}</p>

                <div style="display: flex; justify-content: space-around; margin-top: 4px;">

                {%for eachStar in each_book_and_genres.rating%}

                    {% if eachStar == 1 %}
                        <img src="{% static 'images/star-filled.png' %}" style="width: 14%">
                    {% else %}
                        <img src="{% static 'images/star-outline.png' %}" style="width: 14%">
                    {% endif %}

                {% endfor %}

                </div>

                <div style="display: flex; flex-wrap: wrap">
                {% for eachGenre in each_book_and_genres.genres%}
                    <div class="genre-container" style="background-color: {{eachGenre.color}}; 
                    display: flex; padding: 0px 5px 0px 5px; margin-right: 5px">
                        <p style="text-align: left; font-size:12px">{{eachGenre.title}}</p>
                    </div>
                    {% endfor %}
                </div>
            </div>

        </div>
        {% else %}
        <div class="book" style="visibility: hidden">
        </div>
        {% endif %}
    {% endfor %}
    </div>
{% endfor %}

templates/each_suggestion.html
<div id="dynamic-item-details">

{% for eachSuggestion in suggested_book_titles%}
    <button type="button" onclick="selectOption(this)" style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis; width: 100%;">
        <span> {{eachSuggestion.book_title}}</span> 
        <span> {{eachSuggestion.book_author}}</span> 
        <span> {{eachSuggestion.book_cover}}</span> 
    </button>
    
{% endfor %}

</div>

<script>
function selectOption(element) {
    const all_details = element.children;

    const book_title = all_details[0].innerText;
    const book_author = all_details[1].innerText;
    const book_cover = all_details[2].innerText;

    document.getElementById("book_title").value = book_title;
    document.getElementById("book_author").value = book_author;
    document.getElementById("book_cover").value = book_cover;

    document.getElementById("current_book_cover").src = book_cover;

    all_options = document.getElementById("suggestions");
    all_options.style.display = 'none';
}

</script>

templates/index.html
<html>
    <head>
        <title>Book Tracker</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Libertinus+Sans:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Squada+One&display=swap" rel="stylesheet">

        <script src="https://unpkg.com/htmx.org@1.9.12"></script>

        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">

        <style>
            .genre-select {
                display: flex;
            }

            .active {
                background-color: #feeffe !important;
            }

            .book-list {
                margin-top: 2px;
                list-style: none;
                padding: 0;
                width: 200px;
                max-height: 200px;
                overflow-y: auto;
                background-color: #fff;
                border-radius: 5px;
                box-shadow: 0 0 5px rgba(0, 0, 0, 0.3);
                pointer-events: none;
                transition: max-height 0.5s ease, opacity 0.5s ease; /* Added transition */
                opacity: 1;
                pointer-events: auto;
            }

            .book-list li {
                padding: 10px;
                border-bottom: 1px solid #ddd;
                transition: background-color 0.3s ease;
            }

            .book-list li:hover {
                background-color: #f0f0f0;
            }

            /* Sticky search bar */
            .search-bar {
                position: sticky;
                top: 0;
                z-index: 1;
                background-color: #fff;
            }

            .search-bar input[type="text"] {
                width: calc(100% - 20px);
                padding: 8px;
                border: 1px solid #ccc;
                border-radius: 5px;
            }

            /* Hide scrollbar */
            .book-list::-webkit-scrollbar {
                display: none;
            }

            .book-list {
                scrollbar-width: none;
            }

            .book-list::-webkit-scrollbar-track {
                display: none;
            }

            .book-list::-webkit-scrollbar-thumb {
                display: none;
            }

            .genre-container {
                width: fit-content;
                border-radius: 15px;
                margin-top: 10px;
                align-items: center;
                height: 25px;
            }

            .star {
                width: 19%;
                box-shadow: none;
                border: none;
                background-color: white;
            }

        </style>

    </head>

    <body>
        
        <div class="container">
            <div class="box left-menu" style="min-height: 100vh;">
                <h1>Book Tracker</h1>
            </div>

            <div class="box right-menu" style="min-height: 100vh;">

                <a href="#popup1">Let me Pop up</a>

                {%block content%}
                {% endblock %}

                <form action="{% url 'books:add_throne' %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Add Throne</button>
                </form>


                <form action="{% url 'books:add_throne' %}" method="post" style="margin: 0px">
                {% csrf_token %}

                <div style="display: flex; margin-left: 10px" id="filters">
                <p style="margin-top: 12px; margin-right: 10px">Filter By: </p>
                <input id ="filters_selected" name="filters_selected" style="display:none" ></input>
                
                {% for each_genre in all_used_genres%}
                    <button class="genre-container" style="background-color: {{each_genre.color}}; 
                        display: flex; padding: 0px 5px 0px 5px; margin-right: 5px;" onclick="select_filter(this)"
                        hx-post="/filter_view/", hx-target="#view-books", swap="innerHTML" type="button">

                        {% comment %} hx-post="/books/filter-view/", hx-target="#view-books", swap="innerHTML" {% endcomment %}

                            <p style="text-align: left; font-size:12px">{{each_genre.title}}</p>
                    </button>
                {% endfor %}
                </div>
                </form>
                
                <div id="view-books">
                {% include 'all_books_view.html' %}
                </div>

        </div>
        </div>

        <script>
            document.addEventListener("DOMContentLoaded", function() {
                document.getElementById("add_book").addEventListener("keydown", function(event) {
                    if (event.key === "Enter") {
                        event.preventDefault();
                    }
                });

                const book_title_field = document.getElementById("book_title");

                book_title_field.addEventListener("keydown", function(event) {
                    if (event.key === "Enter") {
                        event.preventDefault();
                        document.getElementById("generate_suggestions").click();
                        document.getElementById("yello").innerText = book_title_field.value;
                        document.getElementById("suggestions").style.display = "block";
                    }
                });
            });

            filters_selected = []
            function select_filter(element) {
                element_text = element.children[0].innerText;
                if (filters_selected.includes(element_text)) {
                   element.classList.remove("active");
                   filters_selected = filters_selected.filter(item => item !== element_text);
                } else {
                    element.classList.add("active");
                    filters_selected.push(element_text);
                }
                document.getElementById("filters_selected").value = filters_selected;
            }
        </script>
    </body>
</html>

templates/maingbooks.html
<html> 
    <body> Hello 

     
    </body> 
    
</html>

templates/user_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
</head>
<body>
<p>Hello</p>
<form action="{% url 'books:create_account' %}"  method="post">
  {% csrf_token %}
  
  <div class="container">
    <h1>create accoutn</h1>
    <label for="username"><b>User Name</b></label>
    <input type="text" placeholder="Enter User Name: " name="username" required>
    <label for="psw"><b>Password</b></label>
    <input type="password" placeholder="Enter Password: " name="password" required>
    <div>
      <button class="button" type="submit">Login</button>
    </div>
  </div>

</form>
</body>
</html>

templates/user_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
</head>
<body>
<p>Hello</p>
<form action="{% url 'books:login' %}"  method="post">
  {% csrf_token %}
  
  <div class="container">
    <h1>Login</h1>
    <label for="username"><b>User Name</b></label>
    <input type="text" placeholder="Enter User Name: " name="username" required>
    <label for="psw"><b>Password</b></label>
    <input type="password" placeholder="Enter Password: " name="password" required>
    <div>
      <button class="button" type="submit">Login</button>
    </div>
  </div>

</form>
</body>
</html>